export const DEFAULT_CENTRES = [
  {
    id: "thika-stadium-grounds",
    name: "Thika Stadium Grounds",
    place: "Thika",
    county: "Kiambu",
    status: "Open today",
    latitude: -1.0396,
    longitude: 37.0693,
    landmark: "Near Blue Post roundabout",
  },
  {
    id: "juja-town-hall",
    name: "Juja Town Hall",
    place: "Juja",
    county: "Kiambu",
    status: "Opens 8:00 AM",
    latitude: -1.1024,
    longitude: 37.0146,
    landmark: "Town Hall entrance",
  },
  {
    id: "ruiru-social-hall",
    name: "Ruiru Social Hall",
    place: "Ruiru",
    county: "Kiambu",
    status: "Open today",
    latitude: -1.1461,
    longitude: 36.9603,
    landmark: "Near Ruiru market",
  },
  {
    id: "kiambu-market-centre",
    name: "Kiambu Market Centre",
    place: "Kiambu",
    county: "Kiambu",
    status: "Open today",
    latitude: -1.1714,
    longitude: 36.8356,
    landmark: "Main market gate",
  },
  {
    id: "githurai-chiefs-camp",
    name: "Githurai Chiefs Camp",
    place: "Githurai",
    county: "Nairobi",
    status: "Opens 8:30 AM",
    latitude: -1.2054,
    longitude: 36.9013,
    landmark: "Near Githurai 45 stage",
  },
  {
    id: "muranga-social-hall",
    name: "Murang'a Social Hall",
    place: "Murang'a",
    county: "Murang'a",
    status: "Open today",
    latitude: -0.7216,
    longitude: 37.1521,
    landmark: "Town centre",
  },
  {
    id: "nyeri-town-centre",
    name: "Nyeri Town Centre",
    place: "Nyeri",
    county: "Nyeri",
    status: "Opens 9:00 AM",
    latitude: -0.4197,
    longitude: 36.9476,
    landmark: "Near Nyeri bus park",
  },
];

export const DEFAULT_GROUPS = [
  {
    id: "thika-mbogi",
    name: "Thika Mbogi",
    area: "Thika",
    meetingPoint: "Thika stage",
    departureTime: "2026-04-19T10:00",
    memberCount: 18,
    centerId: "thika-stadium-grounds",
  },
  {
    id: "juja-campus-wave",
    name: "Juja Campus Wave",
    area: "Juja",
    meetingPoint: "Campus main gate",
    departureTime: "2026-04-18T09:00",
    memberCount: 26,
    centerId: "juja-town-hall",
  },
  {
    id: "ruiru-youth-squad",
    name: "Ruiru Youth Squad",
    area: "Ruiru",
    meetingPoint: "Ruiru market",
    departureTime: "2026-04-19T08:30",
    memberCount: 12,
    centerId: "ruiru-social-hall",
  },
  {
    id: "kiambu-town-linkup",
    name: "Kiambu Town Linkup",
    area: "Kiambu",
    meetingPoint: "Kiambu market gate",
    departureTime: "2026-04-20T08:15",
    memberCount: 9,
    centerId: "kiambu-market-centre",
  },
];

export const REGISTRATION_CHECKLIST = [
  "Original national ID or waiting card",
  "A charged phone and enough airtime for calls",
  "Fare for the round trip",
  "A friend or group contact in case plans change",
];
